language: python
python:
  - 3.6
before_install:
  - '[ "${TRAVIS_TAG}" == "" ] || echo "${TRAVIS_TAG}" > VERSION.txt'
install:
  - pip install tox
script:
  - make test
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    condition: -n $TRAVIS_TAG || -n $TRAVIS_BRANCH
sudo: required
services:
  - docker
