language: python
python:
  - 3.6
before_install:
  - '[ "${TRAVIS_TAG}" == "" ] || echo "${TRAVIS_TAG}" > VERSION.txt'
install:
  - make install
script:
  - make test
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
    tags: true
